version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # default set (gosimple, unused now part of staticcheck)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    # formatting handled by formatters section
    # bugs
    - bodyclose
    - nilerr
    - sqlclosecheck
    - errorlint
    - rowserrcheck
    # security
    - gosec
    # style
    - gocritic
    - unconvert
    - misspell
    - dupword
    # complexity
    - cyclop
    - funlen
    - nestif
    # modern go (1.22+)
    - copyloopvar
    - intrange
    # performance
    - prealloc
    - wastedassign

  settings:
    goimports:
      local-prefixes:
        - r-cli
    cyclop:
      max-complexity: 10
    funlen:
      lines: 80
      statements: 50
    nestif:
      min-complexity: 5
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - whyNoLint
    gosec:
      excludes:
        - G104
        - G304
        - G704
        - G705

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - r-cli

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - funlen
